version: '3'

services:
  api:
    build: .
    command: uvicorn --host 0.0.0.0 --proxy-headers --forwarded-allow-ips * src:app
    depends_on:
      - db
      - redis
    volumes:
      - ./:/app
    ports:
      - 127.0.0.1:8006:8000
    environment:
      - PSQL_DSN
      - REDIS_URL
      - JWT_KEY
      - FERNET_KEY
      - SHARD_COUNT

  db:
    image: postgres:14-alpine
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - ./schema:/docker-entrypoint-initdb.d
      - ./data/postgres:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    command: redis-server --loglevel warning
    volumes:
      - ./data/redis:/data
