on:
  push:
    branches:
      - stardust

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2.1.4
      - name: install
        run: npm clean-install
      - name: build
        run: npm run build
      - name: deploy
        env:
          CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
        run: npm run deploy
